"""table BookIssue updated to set default values in issue_date and due_date

Revision ID: 856dc3416ec9
Revises: 428ee298c4a5
Create Date: 2025-02-03 12:39:58.188798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856dc3416ec9'
down_revision: Union[str, None] = '428ee298c4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
