"""bookgenres renamed to book_genres

Revision ID: bb4666a1515f
Revises: f9ada253cde3
Create Date: 2025-01-29 12:25:25.503561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4666a1515f'
down_revision: Union[str, None] = 'f9ada253cde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
