"""add Genre ad BookGenre tables2

Revision ID: d633d7d236f3
Revises: 77460a67beea
Create Date: 2025-01-28 15:29:22.318708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd633d7d236f3'
down_revision: Union[str, None] = '77460a67beea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
